### ISSUE TITLE
Original masks of Deepfashion model dataset ?

### ISSUE THREAD

**Issue by kkpetra** [zhaofang0627/HPBTT#5]
Thanks for your great work!

I am trying to train the fashion model and there needs a seg folder here:
`self.mask_ori_dir = osp.join(self.data_dir, 'seg')`

I think it should be the ground truth mask? How can I get these? Would you share the method that you used?

**Comment by zhaofang0627** [comment]
Hi,

Yes, it is the ground truth mask provided by DeepFashion dataset. You can get it from [here](https://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html).

**Comment by kkpetra** [comment]
Thank you for your reply!  

But I found only highres images have masks which size is not 255x255 and some images in your train_list do not have ground truth masks in the dataset, how to solve this problem? Did you process those masks before using them? 

Hoping for the reply again!

**Comment by kkpetra** [comment]
> Hi,
> 
> Yes, it is the ground truth mask provided by DeepFashion dataset. You can get it from [here](https://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html).

Thank you for your reply!

But I found only highres images have masks which size is not 255x255 and some images in your train_list do not have ground truth masks in the dataset, how to solve this problem? Did you process those masks before using them?

Hoping for the reply again!

**Comment by zhaofang0627** [comment]
Hi,

Sorry, since it's been long time since the project ended, if I remember correctly, we use [Graphonomy](https://github.com/Gaoyiminggithub/Graphonomy) to get these masks, which have enough accuracy.

**Comment by kkpetra** [comment]
> 

Thank you!
